# Generated by Django 5.2.3 on 2025-08-23 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='discount_percent',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Процент скидки для этого магазина', max_digits=5, verbose_name='Скидка магазина (%)'),
        ),
    ]
