# Generated by Django 5.2.3 on 2025-08-23 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_alter_category_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='dispose',
        ),
        migrations.AlterField(
            model_name='product',
            name='parsed_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Со скидкой'),
        ),
    ]
