# Generated by Django 5.2.3 on 2025-08-23 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_remove_product_dispose_alter_product_parsed_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='parsed_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name=' скидкой'),
        ),
    ]
