# Generated by Django 5.2.3 on 2025-08-23 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_calculationmethod_designer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calculationmethod',
            name='code',
        ),
    ]
