# Generated by Django 5.2.3 on 2025-08-24 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_remove_calculationmethod_code'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='calculationmethod',
            options={'verbose_name': 'Способ оплаты раб', 'verbose_name_plural': 'Способы оплаты раб'},
        ),
        migrations.AlterModelOptions(
            name='designer',
            options={'verbose_name': 'Проектировщик', 'verbose_name_plural': 'Проектировщики'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Элемент', 'verbose_name_plural': 'Элементы'},
        ),
        migrations.AlterModelOptions(
            name='store',
            options={'verbose_name': 'Магазин', 'verbose_name_plural': 'Магазины'},
        ),
        migrations.AddField(
            model_name='category',
            name='category_type',
            field=models.CharField(choices=[('hinges', 'Петли'), ('runners', 'Направляющие'), ('other', 'Другое')], default='other', max_length=20, verbose_name='Тип категории'),
        ),
        migrations.AddField(
            model_name='product',
            name='mounting_type',
            field=models.CharField(blank=True, choices=[('', '--- Выберите тип ---')], default='', max_length=20, verbose_name='Тип крепления'),
        ),
        migrations.AlterField(
            model_name='product',
            name='parsed_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Цена со скидкой'),
        ),
    ]
