# Generated by Django 5.2.3 on 2025-08-24 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_alter_calculationmethod_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='category_type',
        ),
        migrations.AlterField(
            model_name='product',
            name='mounting_type',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Тип крепления'),
        ),
    ]
