# Generated by Django 5.2.3 on 2025-08-24 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_remove_category_category_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='mounting_type',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Тип крепления петли'),
        ),
    ]
