# Generated by Django 5.2.3 on 2025-08-24 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_alter_product_mounting_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='answer_type',
            field=models.CharField(blank=True, choices=[('', '--- Выберите ответку ---'), ('прямая', 'Прямая'), ('крестообразная', 'Крестообразная')], default='', max_length=20, verbose_name='Ответка'),
        ),
    ]
