# Generated by Django 5.2.3 on 2025-08-24 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_product_answer_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='mounting_type',
        ),
        migrations.AddField(
            model_name='product',
            name='hinge_type',
            field=models.CharField(blank=True, choices=[('', '--- Выберите тип ---'), ('Накладная', 'Накладная'), ('Полунакладная', 'Полунакладная'), ('Внутренняя', 'Внутренняя')], default='', max_length=50, verbose_name='Тип крепления петли'),
        ),
        migrations.AddField(
            model_name='product',
            name='runner_type',
            field=models.CharField(blank=True, choices=[('', '--- Выберите тип ---'), ('Шариковые', 'Шариковые'), ('Роликовые', 'Роликовые')], default='', max_length=50, verbose_name='Тип направляющих'),
        ),
        migrations.AlterField(
            model_name='product',
            name='answer_type',
            field=models.CharField(blank=True, choices=[('', '--- Выберите ответку ---'), ('Прямая', 'Прямая'), ('Крестообразная', 'Крестообразная')], default='', max_length=50, verbose_name='Тип ответки'),
        ),
    ]
