# Generated by Django 5.2.3 on 2025-08-24 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0012_remove_product_mounting_type_product_hinge_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='answer_type',
        ),
        migrations.RemoveField(
            model_name='product',
            name='hinge_type',
        ),
        migrations.RemoveField(
            model_name='product',
            name='runner_type',
        ),
        migrations.AddField(
            model_name='product',
            name='mounting_type',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Тип'),
        ),
    ]
