# Generated by Django 5.2.3 on 2025-08-24 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0013_remove_product_answer_type_remove_product_hinge_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='response_type',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Тип ответки'),
        ),
        migrations.AlterField(
            model_name='product',
            name='mounting_type',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Тип'),
        ),
    ]
