# Generated by Django 5.2.3 on 2025-08-24 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0014_product_response_type_alter_product_mounting_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='runner_size',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Размер направляющих'),
        ),
    ]
