# Generated by Django 5.2.3 on 2025-08-24 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0015_product_runner_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='hinge_angle',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Угол открывания'),
        ),
        migrations.AddField(
            model_name='product',
            name='hinge_closing_type',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Тип закрывания'),
        ),
    ]
