# Generated by Django 5.2.3 on 2025-08-25 01:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0016_product_hinge_angle_product_hinge_closing_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='KitchenProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=100, verbose_name='Заказ №')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма')),
                ('advance', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Аванс')),
                ('advance_yura', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Аванс у Юры')),
                ('advance_oleg', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Аванс у Олега')),
                ('customer_balance', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Остаток заказчика')),
                ('delivery_date', models.DateField(blank=True, null=True, verbose_name='Дата поставки')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='KitchenItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(verbose_name='№')),
                ('name', models.CharField(max_length=200, verbose_name='Наименование товара')),
                ('size', models.CharField(blank=True, max_length=100, verbose_name='Размер')),
                ('quantity', models.IntegerField(default=0, verbose_name='Кол-во')),
                ('color', models.CharField(blank=True, max_length=100, verbose_name='Цвет')),
                ('supplier', models.CharField(blank=True, max_length=100, verbose_name='Поставщик')),
                ('payment_yura', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Оплата Юра')),
                ('payment_oleg', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Оплата Олег')),
                ('delivery_time', models.CharField(blank=True, max_length=100, verbose_name='Срок доставки')),
                ('arrival_to_warehouse', models.CharField(blank=True, max_length=100, verbose_name='Приход на склад')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='website.kitchenproject')),
            ],
            options={
                'ordering': ['number'],
            },
        ),
    ]
