# Generated by Django 5.2.3 on 2025-08-25 02:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0017_kitchenproject_kitchenitem'),
    ]

    operations = [
        migrations.DeleteModel(
            name='KitchenItem',
        ),
        migrations.DeleteModel(
            name='KitchenProject',
        ),
    ]
