# Generated by Django 5.2.3 on 2025-08-25 07:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0018_delete_kitchenitem_delete_kitchenproject'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='products',
            field=models.ManyToManyField(blank=True, related_name='records', to='website.product', verbose_name='Комплектующие'),
        ),
        migrations.CreateModel(
            name='RecordProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.product')),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.record')),
            ],
            options={
                'unique_together': {('record', 'product')},
            },
        ),
    ]
