# Generated by Django 5.2.3 on 2025-08-25 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0019_record_products_recordproduct'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RecordProduct',
        ),
    ]
