# Generated by Django 5.2.3 on 2025-08-25 20:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0021_recordproduct'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnplannedExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=200, verbose_name='Предмет расхода')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unplanned_expenses', to='website.record', verbose_name='Запись')),
            ],
            options={
                'verbose_name': 'Непланируемый расход',
                'verbose_name_plural': 'Непланируемые расходы',
                'ordering': ['-created_at'],
            },
        ),
    ]
