# Generated by Django 5.2.3 on 2025-08-25 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0022_unplannedexpense'),
    ]

    operations = [
        migrations.AddField(
            model_name='unplannedexpense',
            name='spent_by',
            field=models.CharField(choices=[('Юра', 'Юра'), ('Олег', 'Олег')], default='Юра', max_length=50, verbose_name='Кто потратил'),
        ),
    ]
