# Generated by Django 5.2.3 on 2025-08-25 21:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0023_unplannedexpense_spent_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecordExcelFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('excel_file', models.FileField(upload_to='records_excel/', verbose_name='Excel файл комплектации')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('record', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='excel_file', to='website.record', verbose_name='Запись')),
            ],
            options={
                'verbose_name': 'Excel файл записи',
                'verbose_name_plural': 'Excel файлы записей',
            },
        ),
    ]
