# Generated by Django 5.2.3 on 2025-08-25 22:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0024_recordexcelfile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RecordExcelFile',
        ),
    ]
