# Generated by Django 5.2.3 on 2025-08-25 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0025_delete_recordexcelfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='recordproduct',
            name='buyer',
            field=models.CharField(choices=[('Юра', 'Юра'), ('Олег', 'Олег')], default='Юра', max_length=10, verbose_name='Кто купил'),
        ),
    ]
