# Generated by Django 5.2.3 on 2025-08-26 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0026_recordproduct_buyer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recordproduct',
            name='quantity',
            field=models.IntegerField(default=1, verbose_name='Количество'),
        ),
    ]
