# Generated by Django 5.2.3 on 2025-09-09 02:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0027_alter_recordproduct_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название плиты')),
                ('material', models.CharField(choices=[('ЛДСП', 'ЛДСП'), ('МДФ', 'МДФ'), ('Пленка', 'Пленка'), ('Другой', 'Другой материал')], default='ЛДСП', max_length=20, verbose_name='Материал')),
                ('thickness', models.DecimalField(decimal_places=2, help_text='Толщина в миллиметрах', max_digits=5, verbose_name='Толщина (мм)')),
                ('color', models.CharField(blank=True, max_length=50, verbose_name='Цвет/Оттенок')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('price_per_square_meter', models.DecimalField(decimal_places=2, help_text='Цена за квадратный метр', max_digits=10, verbose_name='Цена за м²')),
            ],
            options={
                'verbose_name': 'Плита',
                'verbose_name_plural': 'Плиты',
                'ordering': ['material', 'thickness', 'name'],
            },
        ),
        migrations.CreateModel(
            name='RecordPlita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, default=1, help_text='Количество в квадратных метрах', max_digits=10, verbose_name='Количество (м²)')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('plita', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.plita')),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.record')),
            ],
            options={
                'verbose_name': 'Используемая плита',
                'verbose_name_plural': 'Используемые плиты',
                'unique_together': {('record', 'plita')},
            },
        ),
        migrations.AddField(
            model_name='record',
            name='plitas',
            field=models.ManyToManyField(blank=True, related_name='records', through='website.RecordPlita', to='website.plita', verbose_name='Используемые плиты'),
        ),
    ]
