# Generated by Django 5.2.3 on 2025-09-09 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0028_plita_recordplita_record_plitas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plita',
            name='description',
        ),
    ]
