# Generated by Django 5.2.3 on 2025-10-17 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0029_remove_plita_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='recordproduct',
            name='custom_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Своя цена за единицу'),
        ),
    ]
