# Generated by Django 5.2.3 on 2025-10-17 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0030_recordproduct_custom_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='email',
        ),
        migrations.AddField(
            model_name='record',
            name='telegram',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Telegram'),
        ),
    ]
