# Generated by Django 5.2.3 on 2025-10-17 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0031_remove_record_email_record_telegram'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='price',
        ),
        migrations.AddField(
            model_name='record',
            name='advance',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Аванс'),
        ),
        migrations.AddField(
            model_name='record',
            name='contract_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Сумма по договору'),
        ),
    ]
