# Generated by Django 5.2.3 on 2025-10-17 21:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0032_remove_record_price_record_advance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='designer',
            name='percentage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Процент от договора'),
        ),
        migrations.AddField(
            model_name='designer',
            name='rate_per_square_meter',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Ставка за м²'),
        ),
        migrations.AddField(
            model_name='record',
            name='designer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='website.designer', verbose_name='Проектировщик'),
        ),
    ]
