# Generated by Django 5.2.3 on 2025-10-17 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0033_designer_percentage_designer_rate_per_square_meter_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='designer_info_cached',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Инфо проектировщика (кеш)'),
        ),
        migrations.AddField(
            model_name='record',
            name='designer_salary_cached',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Зарплата проектировщика (кеш)'),
        ),
        migrations.AddField(
            model_name='record',
            name='last_calculated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата расчета'),
        ),
        migrations.AddField(
            model_name='record',
            name='total_area',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True, verbose_name='Общая площадь (м²)'),
        ),
    ]
