# Generated by Django 5.2.3 on 2025-10-17 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0034_record_designer_info_cached_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='designer_info_cached',
        ),
        migrations.RemoveField(
            model_name='record',
            name='designer_salary_cached',
        ),
        migrations.RemoveField(
            model_name='record',
            name='last_calculated_at',
        ),
        migrations.RemoveField(
            model_name='record',
            name='total_area',
        ),
        migrations.AddField(
            model_name='record',
            name='designer_manual_salary',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Зарплата проектировщика (пог. метр)'),
        ),
    ]
