# Generated by Django 5.2.3 on 2025-10-17 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0035_remove_record_designer_info_cached_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='margin_oleg',
            field=models.BooleanField(default=True, verbose_name='Моржа Олег'),
        ),
        migrations.AddField(
            model_name='record',
            name='margin_yura',
            field=models.BooleanField(default=True, verbose_name='Моржа Юра'),
        ),
    ]
