# Generated by Django 5.2.3 on 2025-10-18 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0036_record_margin_oleg_record_margin_yura'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='status',
            field=models.CharField(choices=[('otrisovka', 'Отрисовка'), ('zhdem_material', 'Ждем прибытия материала'), ('priekhal_v_ceh', 'Приехал в цех'), ('na_raspile', 'На распиле'), ('zakaz_gotov', 'Заказ готов')], default='otrisovka', max_length=20, verbose_name='Статус заказа'),
        ),
    ]
