# Generated by Django 5.2.3 on 2025-10-19 11:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0037_alter_record_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='designer',
            options={'verbose_name': 'Рабочий', 'verbose_name_plural': 'Рабочие'},
        ),
        migrations.AddField(
            model_name='designer',
            name='profession',
            field=models.CharField(choices=[('рабочие', 'Рабочие'), ('дизайнер', 'Дизайнер'), ('цех', 'Цех'), ('сборщики', 'Сборщики'), ('доставка', 'Доставка')], default='рабочие', max_length=20, verbose_name='Профессия'),
        ),
        migrations.AlterField(
            model_name='record',
            name='designer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='website.designer', verbose_name='Рабочий'),
        ),
        migrations.AlterField(
            model_name='record',
            name='designer_manual_salary',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Зарплата рабочего (пог. метр)'),
        ),
    ]
