# Generated by Django 5.2.3 on 2025-10-19 11:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0038_alter_designer_options_designer_profession_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='assembler_worker',
            field=models.ForeignKey(blank=True, limit_choices_to={'profession': 'сборщики'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assembler_records', to='website.designer', verbose_name='Сборщик'),
        ),
        migrations.AddField(
            model_name='record',
            name='delivery_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Цена доставки'),
        ),
        migrations.AddField(
            model_name='record',
            name='designer_worker',
            field=models.ForeignKey(blank=True, limit_choices_to={'profession': 'дизайнер'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='designer_records', to='website.designer', verbose_name='Дизайнер'),
        ),
        migrations.AddField(
            model_name='record',
            name='workshop_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Цена цеха'),
        ),
    ]
