# Generated by Django 5.2.3 on 2025-10-19 11:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0039_record_assembler_worker_record_delivery_price_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='designer',
            options={'verbose_name': 'Проектировщик', 'verbose_name_plural': 'Проектировщики'},
        ),
        migrations.AlterField(
            model_name='record',
            name='designer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='website.designer', verbose_name='Проектировщик'),
        ),
        migrations.AlterField(
            model_name='record',
            name='designer_manual_salary',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Зарплата проектировщика (пог. метр)'),
        ),
    ]
