# Generated by Django 5.2.3 on 2025-10-19 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0040_alter_designer_options_alter_record_designer_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='designer',
            options={'verbose_name': 'Рабочий', 'verbose_name_plural': 'Рабочие'},
        ),
        migrations.AlterField(
            model_name='designer',
            name='profession',
            field=models.CharField(choices=[('проектировщик', 'Проектировщик'), ('дизайнер', 'Дизайнер'), ('цех', 'Цех'), ('сборщики', 'Сборщики'), ('доставка', 'Доставка')], default='проектировщик', max_length=20, verbose_name='Профессия'),
        ),
    ]
