# Generated by Django 5.2.3 on 2025-10-19 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0041_alter_designer_options_alter_designer_profession'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='assembler_worker_manual_salary',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Погонные метры сборщика'),
        ),
        migrations.AddField(
            model_name='record',
            name='designer_worker_manual_salary',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Погонные метры дизайнера'),
        ),
        migrations.AlterField(
            model_name='record',
            name='designer_manual_salary',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Погонные метры проектировщика'),
        ),
    ]
