# Generated by Django 5.2.3 on 2025-10-19 12:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0042_record_assembler_worker_manual_salary_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='designer',
            name='method',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='website.calculationmethod', verbose_name='Метод расчета'),
        ),
    ]
