# Generated by Django 5.2.3 on 2025-10-19 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0043_alter_designer_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calculationmethod',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='Название метода'),
        ),
    ]
