# Generated by Django 5.2.3 on 2025-10-20 01:20

from django.db import migrations


def merge_duplicate_calculation_methods(apps, schema_editor):
    """Объединяет дублирующиеся методы расчета зарплаты"""
    CalculationMethod = apps.get_model('website', 'CalculationMethod')
    Designer = apps.get_model('website', 'Designer')
    
    # Находим методы расчета
    try:
        pogonny_metr = CalculationMethod.objects.get(name='Погонный метр')
        kvadratny_metr = CalculationMethod.objects.get(name='За квадратный метр')
        
        # Переводим всех рабочих с "За квадратный метр" на "Погонный метр"
        Designer.objects.filter(method=kvadratny_metr).update(method=pogonny_metr)
        
        # Удаляем дублирующий метод
        kvadratny_metr.delete()
        
    except CalculationMethod.DoesNotExist:
        # Если методы не найдены, ничего не делаем
        pass


def reverse_merge_calculation_methods(apps, schema_editor):
    """Обратная операция - не реализована, так как данные уже объединены"""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0044_alter_calculationmethod_name'),
    ]

    operations = [
        migrations.RunPython(
            merge_duplicate_calculation_methods,
            reverse_merge_calculation_methods,
        ),
    ]
