# Generated by Django 5.2.3 on 2025-11-12 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0046_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='status',
            field=models.CharField(choices=[('otrisovka', 'Отрисовка'), ('zhdem_material', 'Ждем прибытия материала'), ('priekhal_v_ceh', 'Приехал в цех'), ('na_raspile', 'На распиле'), ('zakaz_gotov', 'Заказ готов')], db_index=True, default='otrisovka', max_length=20, verbose_name='Статус заказа'),
        ),
        migrations.AlterField(
            model_name='unplannedexpense',
            name='spent_by',
            field=models.CharField(choices=[('Юра', 'Юра'), ('Олег', 'Олег')], db_index=True, default='Юра', max_length=50, verbose_name='Кто потратил'),
        ),
    ]
