# Generated by Django 5.2.3 on 2025-11-12 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0047_add_performance_indexes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plita',
            name='material',
            field=models.CharField(default='ЛДСП', help_text='Можно ввести любой материал', max_length=100, verbose_name='Материал'),
        ),
    ]
