# Generated by Django 5.2.3 on 2025-11-12 22:20

import django.db.models.deletion
from django.db import migrations, models


def create_professions_and_migrate_data(apps, schema_editor):
    """Создает профессии и переносит данные из CharField в ForeignKey"""
    Profession = apps.get_model('website', 'Profession')
    Designer = apps.get_model('website', 'Designer')
    
    # Создаем профессии из старых choices
    profession_names = ['проектировщик', 'дизайнер', 'цех', 'сборщики', 'доставка']
    profession_mapping = {}
    
    for name in profession_names:
        profession, created = Profession.objects.get_or_create(name=name)
        profession_mapping[name] = profession
    
    # Переносим данные для всех дизайнеров
    # Используем raw SQL для получения старого значения из profession_old
    from django.db import connection
    with connection.cursor() as cursor:
        cursor.execute("SELECT id, profession_old FROM website_designer WHERE profession_old IS NOT NULL")
        for row in cursor.fetchall():
            designer_id, old_profession = row
            if old_profession and old_profession in profession_mapping:
                designer = Designer.objects.get(id=designer_id)
                designer.profession = profession_mapping[old_profession]
                designer.save()


def reverse_migration(apps, schema_editor):
    """Обратная миграция - не требуется, так как данные будут потеряны"""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0048_allow_custom_plita_materials'),
    ]

    operations = [
        # Шаг 1: Создаем модель Profession
        migrations.CreateModel(
            name='Profession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Название профессии')),
            ],
            options={
                'verbose_name': 'Профессия',
                'verbose_name_plural': 'Профессии',
            },
        ),
        # Шаг 2: Добавляем временное поле для хранения старого значения
        migrations.AddField(
            model_name='designer',
            name='profession_old',
            field=models.CharField(max_length=20, null=True, blank=True),
        ),
        # Шаг 3: Копируем данные из profession в profession_old через SQL
        migrations.RunSQL(
            "UPDATE website_designer SET profession_old = profession;",
            reverse_sql="UPDATE website_designer SET profession_old = NULL;"
        ),
        # Шаг 4: Изменяем поле profession на ForeignKey (пока nullable)
        migrations.AlterField(
            model_name='designer',
            name='profession',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='website.profession', verbose_name='Профессия'),
        ),
        # Шаг 5: Обновляем limit_choices_to для Record (используем profession__name)
        migrations.AlterField(
            model_name='record',
            name='assembler_worker',
            field=models.ForeignKey(blank=True, limit_choices_to={'profession__name': 'сборщики'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assembler_records', to='website.designer', verbose_name='Сборщик'),
        ),
        migrations.AlterField(
            model_name='record',
            name='designer_worker',
            field=models.ForeignKey(blank=True, limit_choices_to={'profession__name': 'дизайнер'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='designer_records', to='website.designer', verbose_name='Дизайнер'),
        ),
        # Шаг 6: Переносим данные из profession_old в profession (ForeignKey)
        migrations.RunPython(create_professions_and_migrate_data, reverse_migration),
        # Шаг 7: Удаляем временное поле
        migrations.RemoveField(
            model_name='designer',
            name='profession_old',
        ),
    ]
