# Generated by Django 5.2.3 on 2025-11-12 22:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0049_convert_profession_to_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='custom_fields',
            field=models.JSONField(blank=True, default=dict, help_text='Хранит значения полей, определенных для категории', verbose_name='Дополнительные характеристики'),
        ),
        migrations.AlterField(
            model_name='product',
            name='hinge_angle',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Угол открывания (устарело)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='hinge_closing_type',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Тип закрывания (устарело)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='mounting_type',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Тип (устарело)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='response_type',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Тип ответки (устарело)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='runner_size',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Размер направляющих (устарело)'),
        ),
        migrations.CreateModel(
            name='CategoryField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название поля')),
                ('field_key', models.SlugField(help_text='Уникальный идентификатор (например: hinge_angle)', max_length=100, verbose_name='Ключ поля')),
                ('field_type', models.CharField(choices=[('text', 'Текст'), ('number', 'Число'), ('select', 'Выбор из списка')], default='text', max_length=20, verbose_name='Тип поля')),
                ('choices', models.TextField(blank=True, help_text="Для типа 'Выбор из списка' - варианты через запятую", null=True, verbose_name='Варианты выбора')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок отображения')),
                ('required', models.BooleanField(default=False, verbose_name='Обязательное поле')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_fields', to='website.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Поле категории',
                'verbose_name_plural': 'Поля категорий',
                'ordering': ['order', 'id'],
                'unique_together': {('category', 'field_key')},
            },
        ),
    ]
