# Generated by Django 5.2.3 on 2025-11-12 23:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0050_add_category_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoryfield',
            name='choices',
            field=models.TextField(blank=True, help_text="Только для типа 'Выбор из списка'. Укажите варианты через запятую, например: Вариант 1, Вариант 2, Вариант 3", null=True, verbose_name='Варианты выбора'),
        ),
        migrations.AlterField(
            model_name='categoryfield',
            name='field_key',
            field=models.SlugField(blank=True, help_text='Автоматически генерируется из названия', max_length=100, verbose_name='Ключ поля'),
        ),
        migrations.AlterField(
            model_name='categoryfield',
            name='field_type',
            field=models.CharField(choices=[('text', 'Текст'), ('number', 'Число'), ('select', 'Выбор из списка')], default='text', help_text='Текст - для обычных значений, Число - для размеров/количеств, Выбор - для списка вариантов', max_length=20, verbose_name='Тип поля'),
        ),
        migrations.AlterField(
            model_name='categoryfield',
            name='name',
            field=models.CharField(help_text='Например: Угол открывания, Тип ответки, Длина', max_length=100, verbose_name='Название поля'),
        ),
        migrations.AlterField(
            model_name='categoryfield',
            name='order',
            field=models.IntegerField(default=0, help_text='Порядок отображения (0 - первый)', verbose_name='Порядок'),
        ),
        migrations.AlterField(
            model_name='categoryfield',
            name='required',
            field=models.BooleanField(default=False, help_text='Обязательно ли заполнять это поле', verbose_name='Обязательное'),
        ),
        migrations.CreateModel(
            name='ProductCharacteristic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название характеристики')),
                ('value', models.CharField(max_length=200, verbose_name='Значение')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='characteristics', to='website.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Характеристика товара',
                'verbose_name_plural': 'Характеристики товара',
                'ordering': ['order', 'id'],
                'unique_together': {('product', 'name')},
            },
        ),
    ]
