# Generated by Django 5.2.3 on 2025-11-12 23:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0051_add_product_characteristics'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductCharacteristic',
        ),
    ]
