# Generated by Django 5.2.3 on 2025-11-12 23:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0052_remove_product_characteristics'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='website.category', verbose_name='Родительская категория'),
        ),
        migrations.CreateModel(
            name='ProductCustomField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название характеристики')),
                ('value', models.CharField(blank=True, max_length=500, verbose_name='Значение')),
                ('field_type', models.CharField(choices=[('text', 'Текст'), ('number', 'Число'), ('select', 'Выбор из списка')], default='text', max_length=20, verbose_name='Тип поля')),
                ('choices', models.TextField(blank=True, help_text="Только для типа 'Выбор из списка'. Варианты через запятую", null=True, verbose_name='Варианты выбора')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_custom_fields', to='website.product', verbose_name='Продукт')),
            ],
            options={
                'verbose_name': 'Индивидуальная характеристика',
                'verbose_name_plural': 'Индивидуальные характеристики',
                'ordering': ['order', 'id'],
            },
        ),
    ]
