# Generated by Django 5.2.3 on 2025-11-12 23:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0053_alter_category_parent_productcustomfield'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='parent',
        ),
    ]
