# Generated by Django 5.2.3 on 2025-11-12 23:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0054_remove_category_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcustomfield',
            name='category_field',
            field=models.ForeignKey(blank=True, help_text='Выберите шаблон из характеристик категории этого продукта', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_custom_fields', to='website.categoryfield', verbose_name='Шаблон характеристики'),
        ),
        migrations.RemoveField(
            model_name='productcustomfield',
            name='choices',
        ),
        migrations.RemoveField(
            model_name='productcustomfield',
            name='field_type',
        ),
        migrations.RemoveField(
            model_name='productcustomfield',
            name='name',
        ),
        migrations.AlterUniqueTogether(
            name='productcustomfield',
            unique_together={('product', 'category_field')},
        ),
    ]
