# Generated by Django 5.2.3 on 2025-11-12 23:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0055_alter_productcustomfield_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoryfield',
            options={'ordering': ['id'], 'verbose_name': 'Поле категории', 'verbose_name_plural': 'Поля категорий'},
        ),
        migrations.RemoveField(
            model_name='categoryfield',
            name='choices',
        ),
        migrations.RemoveField(
            model_name='categoryfield',
            name='order',
        ),
    ]
