# Generated by Django 5.2.3 on 2025-11-13 00:47

import django.db.models.deletion
from django.db import migrations, models


def migrate_plita_to_product(apps, schema_editor):
    """Переносим данные из Plita в Product"""
    Plita = apps.get_model('website', 'Plita')
    Product = apps.get_model('website', 'Product')
    RecordPlita = apps.get_model('website', 'RecordPlita')
    
    # Создаем словарь для маппинга старых ID плит на новые ID продуктов
    plita_to_product_map = {}
    
    # Переносим каждую плиту в Product
    for plita in Plita.objects.all():
        # Создаем новый Product на основе Plita
        product = Product.objects.create(
            name=plita.name,
            is_plita=True,
            material=plita.material,
            thickness=plita.thickness,
            color=plita.color or '',
            price_per_square_meter=plita.price_per_square_meter,
            our_price=plita.price_per_square_meter or 0,  # Используем цену за м² как базовую цену
        )
        plita_to_product_map[plita.id] = product.id
    
    # Обновляем RecordPlita для использования новых Product через raw SQL
    # Это нужно сделать до изменения поля, так как поле еще ссылается на Plita
    from django.db import connection
    with connection.cursor() as cursor:
        for old_plita_id, new_product_id in plita_to_product_map.items():
            cursor.execute(
                "UPDATE website_recordplita SET plita_id = %s WHERE plita_id = %s",
                [new_product_id, old_plita_id]
            )


def reverse_migrate(apps, schema_editor):
    """Обратная миграция - не реализована, так как это деструктивная операция"""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0056_alter_categoryfield_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='color',
            field=models.CharField(blank=True, help_text='Цвет или оттенок плиты', max_length=50, null=True, verbose_name='Цвет/Оттенок'),
        ),
        migrations.AddField(
            model_name='product',
            name='is_plita',
            field=models.BooleanField(default=False, help_text='Отметь, если это плита, а не комплектующее', verbose_name='Это плита'),
        ),
        migrations.AddField(
            model_name='product',
            name='material',
            field=models.CharField(blank=True, help_text='Материал плиты (ЛДСП, МДФ, Пленка и т.д.)', max_length=100, null=True, verbose_name='Материал'),
        ),
        migrations.AddField(
            model_name='product',
            name='price_per_square_meter',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Цена за квадратный метр (для плит)', max_digits=10, null=True, verbose_name='Цена за м²'),
        ),
        migrations.AddField(
            model_name='product',
            name='thickness',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Толщина плиты в миллиметрах', max_digits=5, null=True, verbose_name='Толщина (мм)'),
        ),
        # Переносим данные из Plita в Product
        migrations.RunPython(
            migrate_plita_to_product,
            reverse_migrate,
        ),
        # Обновляем RecordPlita для использования Product
        migrations.AlterField(
            model_name='recordplita',
            name='plita',
            field=models.ForeignKey(limit_choices_to={'is_plita': True}, on_delete=django.db.models.deletion.CASCADE, to='website.product', verbose_name='Плита'),
        ),
        # Обновляем Record.plitas
        migrations.AlterField(
            model_name='record',
            name='plitas',
            field=models.ManyToManyField(blank=True, limit_choices_to={'is_plita': True}, related_name='plita_records', through='website.RecordPlita', to='website.product', verbose_name='Используемые плиты'),
        ),
    ]
