# Generated by Django 5.2.3 on 2025-11-13 00:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0057_merge_plita_into_product'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Plita',
        ),
    ]
