# Generated by Django 5.2.3 on 2025-11-13 00:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0058_remove_plita_model'),
    ]

    operations = [
        # Удаляем поле is_plita из Product
        migrations.RemoveField(
            model_name='product',
            name='is_plita',
        ),
        migrations.AlterField(
            model_name='record',
            name='plitas',
            field=models.ManyToManyField(blank=True, related_name='plita_records', through='website.RecordPlita', to='website.product', verbose_name='Используемые плиты'),
        ),
        migrations.AlterField(
            model_name='recordplita',
            name='plita',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.product', verbose_name='Плита'),
        ),
    ]
