# Generated by Django 5.2.3 on 2025-11-13 00:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0059_replace_is_plita_with_category'),
    ]

    operations = [
        # Поле is_plita_category не было добавлено в миграции 0059, поэтому его не нужно удалять
        # Обновляем только связи, которые уже были изменены в 0059, но без limit_choices_to
        migrations.AlterField(
            model_name='record',
            name='plitas',
            field=models.ManyToManyField(blank=True, related_name='plita_records', through='website.RecordPlita', to='website.product', verbose_name='Используемые плиты'),
        ),
        migrations.AlterField(
            model_name='recordplita',
            name='plita',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.product', verbose_name='Плита'),
        ),
    ]
