# Generated by Django 5.2.3 on 2025-11-13 01:02

from django.db import migrations


def migrate_recordplita_to_recordproduct(apps, schema_editor):
    """Переносим данные из RecordPlita в RecordProduct"""
    RecordPlita = apps.get_model('website', 'RecordPlita')
    RecordProduct = apps.get_model('website', 'RecordProduct')
    
    # Переносим все записи из RecordPlita в RecordProduct
    for rpl in RecordPlita.objects.all():
        # Проверяем, нет ли уже такой записи в RecordProduct
        existing = RecordProduct.objects.filter(
            record=rpl.record,
            product=rpl.plita
        ).first()
        
        if not existing:
            RecordProduct.objects.create(
                record=rpl.record,
                product=rpl.plita,
                quantity=rpl.quantity,
                buyer='Юра',  # Значение по умолчанию
                custom_price=None
            )


def reverse_migrate(apps, schema_editor):
    """Обратная миграция - не реализована"""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0060_remove_is_plita_category'),
    ]

    operations = [
        # Переносим данные из RecordPlita в RecordProduct
        migrations.RunPython(
            migrate_recordplita_to_recordproduct,
            reverse_migrate,
        ),
        # Удаляем поле plitas из Record
        migrations.RemoveField(
            model_name='record',
            name='plitas',
        ),
        # Удаляем модель RecordPlita
        migrations.DeleteModel(
            name='RecordPlita',
        ),
    ]
