# Generated by Django 5.2.3 on 2025-11-13 01:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0061_remove_recordplita'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='color',
        ),
        migrations.RemoveField(
            model_name='product',
            name='material',
        ),
        migrations.RemoveField(
            model_name='product',
            name='price_per_square_meter',
        ),
        migrations.RemoveField(
            model_name='product',
            name='thickness',
        ),
    ]
