# Generated by Django 5.2.3 on 2025-11-13 22:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0062_remove_plita_fields_from_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkerPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('designer', 'Проектировщик'), ('designer_worker', 'Дизайнер'), ('assembler_worker', 'Сборщик')], max_length=20, verbose_name='Роль')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Сумма выплаты')),
                ('is_paid', models.BooleanField(db_index=True, default=False, verbose_name='Оплачено')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата оплаты')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='worker_payments', to='website.record', verbose_name='Запись')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='website.designer', verbose_name='Работник')),
            ],
            options={
                'verbose_name': 'Выплата работнику',
                'verbose_name_plural': 'Выплаты работникам',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['is_paid', '-created_at'], name='website_wor_is_paid_955c67_idx')],
                'unique_together': {('record', 'worker', 'role')},
            },
        ),
    ]
