# Generated by Django 5.2.3 on 2025-11-13 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0063_workerpayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='bank',
            field=models.CharField(blank=True, default='', help_text='Идентификатор Банка Получателя для генерации QR-кода СБП', max_length=100, verbose_name='Банк (Member_ID для СБП)'),
        ),
        migrations.AddField(
            model_name='profile',
            name='phone',
            field=models.CharField(blank=True, default='', help_text='Номер телефона для связи', max_length=20, verbose_name='Номер телефона'),
        ),
    ]
