# Generated by Django 5.2.3 on 2025-11-13 23:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0064_profile_bank_profile_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='bank',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='phone',
        ),
    ]
