# Generated by Django 5.2.3 on 2025-11-13 23:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0065_remove_profile_bank_remove_profile_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='product',
            name='store',
        ),
        migrations.DeleteModel(
            name='Brand',
        ),
        migrations.DeleteModel(
            name='Store',
        ),
    ]
