# Generated by Django 5.2.3 on 2025-12-11 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0067_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='telegram_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Telegram ID'),
        ),
        migrations.AddField(
            model_name='profile',
            name='telegram_verified',
            field=models.BooleanField(default=False, verbose_name='Telegram подтвержден'),
        ),
        migrations.AddField(
            model_name='profile',
            name='verification_code',
            field=models.CharField(blank=True, max_length=6, null=True, verbose_name='Код верификации'),
        ),
    ]
