# Generated by Django 5.2.3 on 2025-12-11 16:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0068_profile_telegram_id_profile_telegram_verified_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_records', to=settings.AUTH_USER_MODEL, verbose_name='Заказчик'),
        ),
    ]
