# Generated by Cursor AI on 2025-12-28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0071_tailscale_invite_link"),
    ]

    operations = [
        migrations.CreateModel(
            name="WorkerPaymentDeduction",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12, verbose_name="Вычет (₽)")),
                ("reason", models.CharField(blank=True, default="", max_length=300, verbose_name="Причина")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Дата создания")),
                (
                    "payment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="deductions",
                        to="website.workerpayment",
                        verbose_name="Выплата",
                    ),
                ),
            ],
            options={
                "verbose_name": "Санкционный вычет",
                "verbose_name_plural": "Санкционные вычеты",
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.AddIndex(
            model_name="workerpaymentdeduction",
            index=models.Index(fields=["payment", "-created_at"], name="website_wor_payment_a1fe61_idx"),
        ),
    ]


